/* eslint-disable*/

import Head from 'next/head';
import React,{useState} from 'react'
import Image from 'next/image'
import axios from 'axios';

export default function Home() {
  const [name, setName] = useState() 
  const [file, setFile] = useState()
  const [images, setImages] = useState()


  const send = async (event) => {
    const data = new FormData()
    // data.append("name", name)
    data.append("file", file[0])
    
    await axios.post("/.netlify/functions/server/profile", data)
      .then(res => {
        // console.log(res);
        setImages(res.data.imgs)
        console.log(images)

      })
      .catch(err => {
        console.log(err)
      })

  }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      <h1>Hello World, Welcome to ER&apos;s backend.</h1>
      <form action="#">
        <label htmlFor='name'>Name</label>
        <input type="text" id="name" onChange={(event) => {
          const {value} = event.target
          setName(value);
          // console.log(value)
        }}/>
        <label htmlFor='file'>File</label>
        <input type="file" id="file" accept=".webp" onChange={(event) => {
          const file = event.target.files
          setFile(file);
          // console.log(file)
        }} />
        <button onClick={(e) => {
          e.preventDefault()
          send()
        }}>Submit</button>
      </form>
      <div>
        {images && <img src={images} />}
      </div>
      </main>

      <footer>
        Hello
      </footer>
    </div>
  )
}
